### ISSUE TITLE
Mistyped emails still create students

### ISSUE THREAD

**Issue by JustKong13** [cornell-dti/zing-lsc#183]
There's an issue where instead of showcasing the net id in the student card it displays the whole email. This group also is getting a fatal error when trying to send emails to. This is in FA23, Math 1110. 
![image](https://github.com/cornell-dti/zing-lsc/assets/64031655/e07f067c-c866-4e5a-b820-8dc1ca7bf2de)

Notes: 
Student was able to submit an invalid email (has @cornell@edu).

**Comment by mluo24** [comment]
Resolved a while back. Issue was in the regex checking for the `.` character in the `.edu` part.

**Comment by mluo24** [comment]
nvm was only recently resolved with #185 but was figured out a while back
