### ISSUE TITLE
Sizing of dashboard class cards still not doing it for me

### ISSUE THREAD

**Issue by hexbabe** [cornell-dti/zing-lsc#51]
<img width="1440" alt="Screen Shot 2022-05-24 at 7 22 21 PM" src="https://user-images.githubusercontent.com/55464069/170165976-6c81d03a-d86b-49b9-b409-1cc12e61eabc.png">

We should fix the styling of these cards

**Comment by Coreball** [comment]
![Screen Shot 2022-05-26 at 23 14 16](https://user-images.githubusercontent.com/22627336/170633933-f6c66cf2-0114-4443-a04b-ec938de19e8a.png)

Left aligned cuz I think it looks nicer when there are multiple rows
